### PR TITLE
Fix Qt 5.12.8 ambiguous calls (QLocale, QDataStream)

### LINKED ISSUE #46: Ambiguous call to QLocale::toString()
Version a8cd9ad316334b6d23755d77066cf63792ae8073

- Kubuntu 20.04
- gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
- Qt 5.12.8
- OpenCascade 7.50
- gmio OFF

```bash
../src/src/base/string_utils.cpp: In static member function ‘static QString Mayo::StringUtils::bytesText(uint64_t, const QLocale&)’:
../src/src/base/string_utils.cpp:97:56: error: call of overloaded ‘toString(uint64_t&)’ is ambiguous
   97 |         return tr("%1%2").arg(locale.toString(sizeBytes), tr("B"));
      |                                                        ^

```

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #46

### CODE REVIEW

File: src/app/recent_files.cpp [hunk 1]
```diff
@@ -100,15 +100,16 @@ QDataStream& operator<<(QDataStream& stream, const RecentFile& recentFile)
...
     return stream;
 }
 
 QDataStream& operator>>(QDataStream& stream, RecentFile& recentFile)
 {
     stream >> recentFile.filepath;
     stream >> recentFile.thumbnail;
-    stream >> recentFile.thumbnailTimestamp;
+    const quint64 thumbnailTimestamp(recentFile.thumbnailTimestamp);
+    stream >> thumbnailTimestamp;
```
Comment (HuguesDelorme) [inline src/app/recent_files.cpp:112]: There is compilation error here reported by the appveyor CI
This should be :
`stream >> reinterpret_cast<qint64&>(recentFile.thumbnailTimestamp);`

**Review by HuguesDelorme — CHANGES_REQUESTED** [review]
Thanks for those changes!
Please fix the compilation error(in `recent_files.cpp`) as proposed so your pull requet can be merged
@++

File: src/app/recent_files.cpp (hunk 1 above)
Comment (VictorLamoine) [reply src/app/recent_files.cpp]: Done!
